/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package colegioperros;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ViguerPC
 */
public class pantalla extends javax.swing.JFrame {

    /**
     * Creates new form pantalla
     */
    Perro perro;
    List<Perro> perros;
    
    public pantalla() {
        initComponents();
        inicio();
        perro = new Perro();
        perros = new ArrayList<Perro>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenida = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JButton();
        botonContarPerros = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        textNombre = new javax.swing.JTextField();
        textLocalidad = new javax.swing.JTextField();
        textDueño = new javax.swing.JTextField();
        TextRaza = new javax.swing.JTextField();
        textContacto = new javax.swing.JTextField();
        textDocDueño = new javax.swing.JTextField();
        textDia = new javax.swing.JTextField();
        labelLocalidad = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelRaza = new javax.swing.JLabel();
        labelDueño = new javax.swing.JLabel();
        labelDocDueño = new javax.swing.JLabel();
        labelContacto = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textRespuesta = new javax.swing.JTextArea();
        botonBuscarPerros = new javax.swing.JButton();
        botonBuscarPerro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bienvenida.setText("Bienvenido");

        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonContarPerros.setText("Contar Perros");
        botonContarPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContarPerrosActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");

        textLocalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLocalidadActionPerformed(evt);
            }
        });

        TextRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextRazaActionPerformed(evt);
            }
        });

        labelLocalidad.setText("Localidad");

        labelNombre.setText("Nombre");

        labelRaza.setText("Raza");

        labelDueño.setText("Dueño");

        labelDocDueño.setText("Doc Dueño");

        labelContacto.setText("Contacto");

        labelDia.setText("Dia");

        textRespuesta.setColumns(20);
        textRespuesta.setRows(5);
        jScrollPane2.setViewportView(textRespuesta);

        botonBuscarPerros.setText("Buscar Perros");
        botonBuscarPerros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPerrosActionPerformed(evt);
            }
        });

        botonBuscarPerro.setText("Buscar Perro");
        botonBuscarPerro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarPerroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAceptar)
                        .addGap(30, 30, 30)
                        .addComponent(botonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(bienvenida)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(botonNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonBuscarPerro))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelLocalidad)
                            .addComponent(labelNombre)
                            .addComponent(labelRaza)
                            .addComponent(labelDueño)
                            .addComponent(labelDocDueño)
                            .addComponent(labelContacto)
                            .addComponent(labelDia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textLocalidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textContacto)
                                .addComponent(textDocDueño, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textDueño, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(textDia, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addComponent(botonBuscarPerros)
                        .addGap(30, 30, 30)
                        .addComponent(botonContarPerros)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bienvenida)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonContarPerros)
                    .addComponent(botonBuscarPerros)
                    .addComponent(botonBuscarPerro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textDocDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDocDueño))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(textContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelContacto)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLocalidad)
                        .addGap(42, 42, 42)
                        .addComponent(labelRaza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDueño)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDia)
                    .addComponent(textDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar)
                    .addComponent(botonAceptar))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
        
        textContacto.setEditable(true);
        textNombre.setEditable(true);
        textLocalidad.setEditable(true);
        textDueño.setEditable(true);
        TextRaza.setEditable(true);
        textContacto.setEditable(true);
        textDocDueño.setEditable(true);
        textDia.setEditable(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        textRespuesta.setText("");
        
             if (textLocalidad.isEditable() && TextRaza.isEditable()
                     && textNombre.isEditable()){
                   perro = new Perro(textLocalidad.getText(), 
                   textNombre.getText(), TextRaza.getText(), 
                   textDueño.getText(), textDocDueño.getText(), 
                   Integer.parseInt(textContacto.getText()), 
                   Integer.parseInt(textDia.getText()));
                   perros.add(perro);
        textContacto.setText("");
        textNombre.setText("");
        textLocalidad.setText("");
        textDueño.setText("");
        TextRaza.setText("");
        textDocDueño.setText("");
        textDia.setText("");
        
        textRespuesta.setText("perro agregado");
        
             }else buscarPerros: if(textLocalidad.isEditable() && !TextRaza.isEditable()
                     && !textNombre.isEditable()){
                 List<String> locPerros = perro.nomPerros(textLocalidad.getText(), perros);
                 
                 String listPerros = "";
                 

                 for (String nomPerro: locPerros){
                 listPerros += nomPerro+", ";
                 }
           textRespuesta.setText(listPerros);
             }else if(!textLocalidad.isEditable() && !TextRaza.isEditable()
                     && textNombre.isEditable()){
                 
                 perro= perro.getPerro(textNombre.getText(), perros);

        textContacto.setText(String.valueOf(perro.getNumContacto()));
        textNombre.setText(perro.getNombre());
        textLocalidad.setText(perro.getLocalidad());
        textDueño.setText(perro.getNombreDueño());
        TextRaza.setText(perro.getRaza());
        textDocDueño.setText(perro.getCedulaDueño());
        textDia.setText(String.valueOf(perro.getDiaAsis()));
  
             }else if (!textLocalidad.isEditable() && TextRaza.isEditable()
                     && !textNombre.isEditable()){
                 
                 int cantPerros = perro.numRaza(TextRaza.getText(), perros);
                 
                 textRespuesta.setText(String.valueOf(cantPerros));
                 
             }
          
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void textLocalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLocalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLocalidadActionPerformed

    private void TextRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextRazaActionPerformed

    private void botonContarPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContarPerrosActionPerformed
        // TODO add your handling code here:
        
        textContacto.setEditable(false);
        textNombre.setEditable(false);
        textLocalidad.setEditable(false);
        textDueño.setEditable(false);
        TextRaza.setEditable(true);
        textContacto.setEditable(false);
        textDocDueño.setEditable(false);
        textDia.setEditable(false);
        
        
    }//GEN-LAST:event_botonContarPerrosActionPerformed

    private void botonBuscarPerrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPerrosActionPerformed
        // TODO add your handling code here:
        textContacto.setEditable(false);
        textNombre.setEditable(false);
        textLocalidad.setEditable(true);
        textDueño.setEditable(false);
        TextRaza.setEditable(false);
        textContacto.setEditable(false);
        textDocDueño.setEditable(false);
        textDia.setEditable(false);
    }//GEN-LAST:event_botonBuscarPerrosActionPerformed

    private void botonBuscarPerroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarPerroActionPerformed
        // TODO add your handling code here:
        textContacto.setEditable(false);
        textNombre.setEditable(true);
        textLocalidad.setEditable(false);
        textDueño.setEditable(false);
        TextRaza.setEditable(false);
        textContacto.setEditable(false);
        textDocDueño.setEditable(false);
        textDia.setEditable(false);
    }//GEN-LAST:event_botonBuscarPerroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla().setVisible(true);
            }
        });
    }
    
    public void inicio(){
        textContacto.setEditable(false);
        textNombre.setEditable(false);
        textLocalidad.setEditable(false);
        textDueño.setEditable(false);
        TextRaza.setEditable(false);
        textContacto.setEditable(false);
        textDocDueño.setEditable(false);
        textDia.setEditable(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextRaza;
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonBuscarPerro;
    private javax.swing.JButton botonBuscarPerros;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonContarPerros;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelContacto;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDocDueño;
    private javax.swing.JLabel labelDueño;
    private javax.swing.JLabel labelLocalidad;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRaza;
    private javax.swing.JTextField textContacto;
    private javax.swing.JTextField textDia;
    private javax.swing.JTextField textDocDueño;
    private javax.swing.JTextField textDueño;
    private javax.swing.JTextField textLocalidad;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextArea textRespuesta;
    // End of variables declaration//GEN-END:variables
}
